src/Entity/Book.php
<?php

namespace App\Entity;

use App\Repository\BookRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=BookRepository::class)
 */
class Book
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=200)
     */
    private $author;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $cover;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $file_book;

    /**
     * @ORM\Column(type="date")
     */
    private $date_reading;

    /**
     * @ORM\ManyToOne(targetEntity=user::class, inversedBy="books")
     * @ORM\JoinColumn(nullable=false)
     */
    private $userId;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getAuthor(): ?string
    {
        return $this->author;
    }

    public function setAuthor(string $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getCover(): ?string
    {
        return $this->cover;
    }

    public function setCover(string $cover): self
    {
        $this->cover = $cover;

        return $this;
    }

    public function getFileBook(): ?string
    {
        return $this->file_book;
    }

    public function setFileBook(string $file_book): self
    {
        $this->file_book = $file_book;

        return $this;
    }

    public function getDateReading(): ?\DateTimeInterface
    {
        return $this->date_reading;
    }

    public function setDateReading(\DateTimeInterface $date_reading): self
    {
        $this->date_reading = $date_reading;

        return $this;
    }

    public function getUserId(): ?User
    {
        return $this->userId;
    }

    public function setUserId(?User $userId): self
    {
        $this->userId = $userId;

        return $this;
    }
}

src/Form/BookType.php
<?php

namespace App\Form;

use App\Entity\Book;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\File;

class BookType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', null,[
                'label'=> 'Название книги',
                'attr' => [
                    'class' => 'form-control',
                    'placeholder' => 'Введите название книги'
                ]
            ])
            ->add('author', null, [
                'label'=> 'Имя автора книги',
                'attr' => [
                    'class' => 'form-control',
                    'placeholder' => 'Введите имя автора'
                ]
            ])
            ->add('cover',FileType::class, [
                'mapped' => false,
                'label'=> 'Обложка',
                'required' => false,
                'constraints' => [
                    new File([
                        'maxSize' => '3M',
                        'mimeTypes' => [
                            'image/jpeg',
                            'image/png',
                        ],
                        'mimeTypesMessage' => 'Загруите изображение в формате .jpg или .png',
                    ])
                ],
                'attr' => [
                    'class' => 'form-control-file',
                ]
            ])
            ->add('file_book',FileType::class, [
                'mapped' => false,
                'label'=> 'Файл книги',
                'required' => false,
                'constraints' => [
                    new File([
                        'maxSize' => '5M',
                        'mimeTypes' => [
                            'application/pdf',
                            'application/msword',
                            'text/plain',
                        ],
                        'mimeTypesMessage' => 'Загруите файл в формате .pdf, .doc, .txt',
                    ])
                ],
                'attr' => [
                    'class' => 'form-control-file',
                ]
            ])
            ->add('date_reading', null, [
                'label'=> 'Дата прочтения',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Book::class,
        ]);
    }
}

src/Controller/BookController.php
<?php

namespace App\Controller;

use App\Entity\Book;
use App\Form\BookType;
use App\Repository\BookRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/book")
 */
class BookController extends AbstractController
{
    /**
     * @Route("/", name="book_index", methods={"GET"})
     */
    public function index(BookRepository $bookRepository): Response
    {
        $books = $this->getDoctrine()
            ->getRepository(Book::class)
            ->findBy(
                ['userId' => $this->getUser()],
                ['date_reading' => 'DESC']);

        return $this->render('book/index.html.twig', [
            'books' => $books,
        ]);
    }

    /**
     * @Route("/new", name="book_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $book = new Book();
        $form = $this->createForm(BookType::class, $book);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $imgFile = $form->get('cover')->getData();
            if ($imgFile) {
                $imgFilename = md5(uniqid()) . '.' . $imgFile->guessExtension();
                $imgFile->move(
                    $this->getParameter('uploadsCover_directory'),
                    $imgFilename
                );

                $book->setCover($imgFilename);
            }

            $textFile = $form->get('file_book')->getData();
            if ($textFile) {
                $textFilename = md5(uniqid()) . '.' . $textFile->guessExtension();
                $textFile->move(
                    $this->getParameter('uploadsText_directory'),
                    $textFilename
                );

                $book->setFileBook($textFilename);
            }

            $book->setUserId($this->getUser());

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($book);
            $entityManager->flush();

            return $this->redirectToRoute('book_index');
        }

        return $this->render('book/new.html.twig', [
            'book' => $book,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}/edit", name="book_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Book $book): Response
    {
        $form = $this->createForm(BookType::class, $book);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $imgFile = $form->get('cover')->getData();
            if ($imgFile) {
                $imgFilename = md5(uniqid()) . '.' . $imgFile->guessExtension();
                $imgFile->move(
                    $this->getParameter('uploadsCover_directory'),
                    $imgFilename
                );

                $book->setCover($imgFilename);
            }

            $textFile = $form->get('file_book')->getData();
            if ($textFile) {
                $textFilename = md5(uniqid()) . '.' . $textFile->guessExtension();
                $textFile->move(
                    $this->getParameter('uploadsText_directory'),
                    $textFilename
                );

                $book->setFileBook($textFilename);
            }
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('book_index');
        }

        return $this->render('book/edit.html.twig', [
            'book' => $book,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="book_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Book $book): Response
    {
        if ($this->isCsrfTokenValid('delete'.$book->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($book);
            $entityManager->flush();
        }

        return $this->redirectToRoute('book_index');
    }
}

templates/book/_delete_form.html.twig
<form method="post" action="{{ path('book_delete', {'id': book.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ book.id) }}">
    <button class="btn">Delete</button>
</form>

templates/book/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary mt-3 mb-3">{{ button_label|default('Создать') }}</button>
{{ form_end(form) }}

templates/book/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Редактирование книги{% endblock %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-xl-6 col-lg-6 col-md-7 col-sm-12 col-12 card mt-5 ml-auto mr-auto">
                <h1 class="text-center">Редактирование книги</h1>
                {{ include('book/_form.html.twig', {'button_label': 'Редактировать'}) }}
            </div>
        </div>
    </div>
{% endblock %}

templates/book/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container">
        <div class="row">
            {% for book in books %}
                <div class="col-xl-4 col-lg-6 col-md-6 col-sm-12 col-12 mt-3 mb-3">
                    <div class="card">
                        <div class="img-container">
                            <img src="{{ asset('uploads/cover/') ~ book.cover }}" class="card-img-top" alt="..."
                                 style="height: 300px">
                        </div>
                        <div class="card-body">
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item">
                                    <h5 class="card-title text-center">
                                        <i class="fa fa-book" aria-hidden="true"></i>
                                        {{ book.name }}
                                    </h5>
                                </li>
                                <li class="list-group-item">
                                    <p class="card-text text-center">
                                        <i class="fa fa-user  mr-1" aria-hidden="true"></i>
                                        {{ book.author }}
                                    </p>
                                </li>
                                <li class="list-group-item">
                                    <p class="card-text text-center">
                                        <i class="fa fa-file" aria-hidden="true"></i>
                                        <a href="{{ asset('uploads/text/') ~ book.fileBook }}">
                                            Файл книги</a>
                                    </p>
                                </li>
                                <li class="list-group-item">
                                    <p class="card-text text-center">
                                        <i class="fa fa-calendar" aria-hidden="true"></i>
                                        {{ book.dateReading|date('Y-m-d') }}
                                    </p>
                                </li>
                            </ul>
                            {% if app.user != null and app.user.username == book.userId.username
                                or is_granted('ROLE_ADMIN') %}
                                <div class="d-flex justify-content-center">
                                    <a href="{{ path('book_edit', {'id':book.id}) }}" class="btn btn-primary mr-2">
                                        Редактировать</a>
                                    <a href="{{ path('book_delete', {'id':book.id}) }}" class="btn btn-primary">
                                        Удалить</a>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            {% endfor %}
            {% if books == null %}
                <h3 class="w-100 mt-5 text-center">Записи не найдены.</h3>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/book/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Создание книги{% endblock %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-xl-6 col-lg-6 col-md-7 col-sm-12 col-12 card mt-5 ml-auto mr-auto">
                <h1 class="text-center">Создание книги</h1>
                    {{ include('book/_form.html.twig') }}
            </div>
        </div>
    </div>
{% endblock %}